[phases.setup]
nixPkgs = ["...", "git", "wget", "gnutar", "rpm2targz"]
[phases.install]
cmds = ["chmod +x start.sh", "./start.sh", "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]
