[phases.setup]
nixPkgs = ["...", "wget", "conda","python311Packages.pip", "gdal"]
cmds = ["chmod +x start.sh", "./start.sh"]
[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install gdal && pip install -r requirements.txt"]
